_default:
    just --list

### Variables ###

NAME := "ask-f1"

### Recipes ###

run:
    uvicorn ask_f1_agent.main:app --host 0.0.0.0 --port 8080 --reload

ask question host="http://localhost:8080":
    curl -X POST \
        -H 'Content-Type: application/json' \
        -d '{"model": "gemini-2.5-flash", "messages": [{"role": "user", "content": "{{question}}"}]}' \
        {{host}}/v1/chat/completions

list-models host="http://localhost:8080":
    curl -X GET \
        {{host}}/v1/models
